baseurl: "/send-to-gitlab-issue" # the subpath of your site, e.g. /blog
url: "https://www.songofcode.com/" # the base hostname & protocol for your site, e.g. http://example.com

kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock

theme: jekyll-theme-clear-stream
